### ISSUE TITLE
ObjectMapperSupplier implementation never loaded

### ISSUE THREAD

**Issue by martinwithaar** [vladmihalcea/hibernate-types#35] opened 2018-06-20 08:09 UTC
**Summary**
A custom `ObjectMapperSupplier` implementation is not loaded on startup.

**Steps to reproduce**
1. Create a custom `ObjectMapperSupplier` implementation that enables serialization features
2. Register the implementation with the `hibernate.types.jackson.object.mapper` setting in your `application.yml` file
3. Run the application

**Expected results**
The enabled serialization features are honored when retrieving json types from the database.

**Actual results**
The enabled serialization features are **not** honored when retrieving json types from the database.

---
## More info
When I add a `throw new RuntimeException();` in the implementation's `get()` method it fails to throw on startup so I know the body is never run.

My `application.yml` is as follows:
```yml
spring:
  profiles:
    active: dev
  rabbitmq:
    listener:
      simple:
        concurrency: 32
        max-concurrency: 48
        prefetch: 16
        acknowledge-mode: auto
        default-requeue-rejected: true
        retry:
          enabled: true
          multiplier: 2
          max-attempts: 10
          stateless: true
          initial-interval: 1s
          max-interval: 30s
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.generate_statistics: false
      hibernate.cache.use_query_cache: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.types.jackson.object.mapper: net.zuluconnect.ZuluconnectObjectMapperSupplier
      hibernate.jdbc.batch_size: 20
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 32
      maximum-pool-size: 48
      idle-timeout: 60000
```

A separate profile-based configuration `application-dev.yml` is also loaded:

```yml
spring:
  rabbitmq:
    host: "0.0.0.0"
    username: guest
    password: guest
  datasource:
    url: jdbc:mariadb://localhost:3306/my_db
    hikari:
      username: root
      password:
logging:
  level:
    org: DEBUG

```

And my `ObjectMapperSupplier` implementation:

```java
package net.zuluconnect;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.vladmihalcea.hibernate.type.util.ObjectMapperSupplier;

@SuppressWarnings("unused")
public class ZuluconnectObjectMapperSupplier implements ObjectMapperSupplier {

    @Override
    public ObjectMapper get() {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.configure(DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT, true);
        objectMapper.configure(DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT, true);
        objectMapper.configure(DeserializationFeature.USE_LONG_FOR_INTS, true);
        return objectMapper;
    }
}
```

**Comment by vladmihalcea** [comment] 2018-06-20 08:18
Thanks for creating the issue. Now, I want you to:

1. Fork the repository.
2. Copy an existing test case and provide the logic that replicates the issue.

Once the issue is replicated, I can start investigating it.

**Comment by vladmihalcea** [comment] 2018-06-29 04:13
Any news about the cause of the issue? Dix you manage to create a replicating test case?

**Comment by martinwithaar** [comment] 2018-07-02 15:52
I haven't found the time to prepare the test case just yet. I hope to be able to provide one somewhere this week.

**Comment by vladmihalcea** [comment] 2018-07-26 08:09
I'll reopen it if a test case will be provided.

**Comment by abdelhakim-atmani** [comment] 2018-10-16 12:18
Based on your documentation the library is looking for the file hibernate-types.properties or hibernate.properties where in a spring context we define the hibernate properties in the application file and all hibernate properties are prefixed by spring.jpa.properties.
It would be nice if the library is used in a spring context, the object mapper defined for spring should be used for the hibernate data types.

**Comment by vladmihalcea** [comment] 2018-10-16 12:28
Just because Spring uses the `spring.jpa.properties`, it does not mean you cannot embed a `hibernate.properties` file in the jar via the `main/resources` folder. Or, you can even use a Java System property too.

**Comment by abdelhakim-atmani** [comment] 2018-10-16 12:47
Yeah I agree but it forces us to define the hibernate properties in 2 different files which is not top.

**Comment by vladmihalcea** [comment] 2018-10-16 12:48
Send me a Pull Request with a fix if think this is worth adding. Thanks.

**Comment by martinwithaar** [comment] 2018-10-19 13:09
I can verify that moving the setting `hibernate.types.jackson.object.mapper` to a separate `hibernate.properties` file fixes my issue but it's strange that it's the only hibernate property that can't be read from a Spring `application.yml`.

**Comment by vladmihalcea** [comment] 2018-10-19 13:17
You should investigate the issue and propose a fix.

**Comment by vladmihalcea** [comment] 2018-10-19 17:11
I will have to try via a Hibernate `Integrator` or something similar to see whether I could register the types when the `SessionFactory` is built to get access to the supplied properties.

**Comment by vladmihalcea** [comment] 2019-08-15 19:32
Closed as it's not possible due to Hibernate limitations. Once [HHH-13103](https://github.com/hibernate/hibernate-orm/pull/2649) gets fixed, it will be possible to address this issue.

**Closed by vladmihalcea** 2019-08-15 19:32 UTC

**Comment by Davio** [comment] 2021-05-25 11:38
It seems that the other issue was fixed: https://github.com/hibernate/hibernate-orm/pull/2649

**Comment by vladmihalcea** [comment] 2021-05-25 12:16
@Davio The change in [HHH-13103](https://github.com/hibernate/hibernate-orm/pull/2649) can only be used from Hibernate 5.5 onwards since it introduces a new class that will throw a `NoClassDefFoundError` on other Hibernate versions.

So, if the [HHH-14020](https://hibernate.atlassian.net/browse/HHH-14020) issue will be fixed, then Hibernate Types could use this feature for older Hibernate versions too. In the meanwhile, there is nothing to be done.
