### ISSUE TITLE
[2.9.0] ListArrayType does not seem to handle null values 

### ISSUE THREAD

**Issue by marceloverdijk** [vladmihalcea/hibernate-types#165] opened 2020-01-13 19:22 UTC
I have PostgreSQL table with the following column:

```
previous_names VARCHAR(255)[] DEFAULT NULL
```

and mapped it to:

```
@Entity
@TypeDefs({
        @TypeDef(name = "list-array", typeClass = ListArrayType.class)
})
public class Project {

    @Column(name = "previous_names")
    @Type(type = "list-array")
    private List<String> previousNames = new ArrayList<>();
}
```

When I query a Project that has previous names it works as expected 👍 

But when querying a Project with a null (`previous_names`) value I get:

```
java.lang.UnsupportedOperationException: The wrapped object null is not an Object[]!
        at com.vladmihalcea.hibernate.type.array.internal.ListArrayTypeDescriptor.wrap(ListArrayTypeDescriptor.java:57) ~[hibernate-types-52-2.9.0.jar:na]
        at com.vladmihalcea.hibernate.type.array.internal.ArraySqlTypeDescriptor$2.doExtract(ArraySqlTypeDescriptor.java:55) ~[hibernate-types-52-2.9.0.jar:na]
        at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
        at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
        at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
        at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:243) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
        at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:329) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
        at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:3041) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
```

**Comment by vladmihalcea** [comment] 2020-01-14 01:32
Looks like a bug. Send me a Pull Request with a fix. Thanks.

**Comment by vladmihalcea** [comment] 2020-01-14 08:54
Duplicate of #164

**Closed by vladmihalcea** 2020-01-14 08:54 UTC
